In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
books_df = pd.read_csv("C:/Users/y/Desktop/Academics/projects/machinelearning/book_recommendation_system/datasets/BX-Books.csv", sep=";", on_bad_lines="skip", encoding="latin-1")

C:\Users\y\AppData\Local\Temp\ipykernel_54332\2316276961.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books_df = pd.read_csv("C:/Users/y/Desktop/Academics/projects/machinelearning/book_recommendation_system/datasets/BX-Books.csv", sep=";", on_bad_lines="skip", encoding="latin-1")

In [3]:
books_df.head(3)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...

In [4]:
books_df = books_df.drop(['Image-URL-S', 'Image-URL-M'], axis=1).reset_index(drop=True)

In [5]:
books_df.head(2)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...

In [6]:
books_df.shape

(271360, 6)

In [7]:
books_df.rename(columns={
    'Book-Title': 'title',
    'Book-Author': 'author',
    'Year-Of-Publication': 'year',
    'Publisher': 'publisher',
    'Image-URL-L': 'image_url',
    'ISBN': 'isbn'
}, inplace=True)

In [8]:
books_df.head(2)

,isbn,title,author,year,publisher,image_url
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...

In [9]:
user_df = pd.read_csv("C:/Users/y/Desktop/Academics/projects/machinelearning/book_recommendation_system/datasets/BX-Users.csv", sep=";", on_bad_lines="skip", encoding="latin-1")

In [10]:
user_df.head(2)

   User-ID                   Location   Age
0        1         nyc, new york, usa   NaN
1        2  stockton, california, usa  18.0

In [11]:
user_df.rename(columns={
    'User-ID': 'user_id',
    'Location': 'location',
    'Age': 'age'
}, inplace=True)

In [12]:
user_df.head(2)

   user_id                   location   age
0        1         nyc, new york, usa   NaN
1        2  stockton, california, usa  18.0

In [13]:
user_df.isnull().value_counts()

user_id  location  age
False    False     False    168096
                   True     110762
Name: count, dtype: int64

In [14]:
ratings_df = pd.read_csv("C:/Users/y/Desktop/Academics/projects/machinelearning/book_recommendation_system/datasets/BX-Book-Ratings.csv", sep=";", on_bad_lines="skip", encoding="latin-1")

In [15]:
ratings_df.head(2)

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5

In [16]:
ratings_df.rename(columns={
    'User-ID': 'user_id',
    'ISBN': 'isbn',
    'Book-Rating': 'rating'
}, inplace=True)

In [17]:
ratings_df.head(2)

   user_id        isbn  rating
0   276725  034545104X       0
1   276726  0155061224       5

In [18]:
ratings_df.shape

(1149780, 3)

In [68]:
user_book_counts = ratings_df['user_id'].value_counts()
heavy_readers = user_book_counts[user_book_counts > 200].index
ratings_df = ratings_df[ratings_df['user_id'].isin(heavy_readers)]

In [70]:
ratings_df.head(2)

      user_id        isbn  rating
1456   277427  002542730X      10
1457   277427  0026217457       0

In [71]:
rating_with_books = ratings_df.merge(books_df, on='isbn')

In [73]:
rating_with_books.head(2)

,user_id,isbn,rating,title,author,year,publisher,image_url
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...
1,277427,0026217457,0,Vegetarian Times Complete Cookbook,Lucy Moll,1995,John Wiley &amp; Sons,http://images.amazon.com/images/P/0026217457.0...

In [75]:
number_rating  = rating_with_books.groupby('title')['rating'].count().reset_index()

In [84]:
number_rating.rename(columns={'no_od_ratings': 'no_of_ratings'}, inplace=True)

In [85]:
number_rating.head(2)

                                               title  no_of_ratings
0   A Light in the Storm: The Civil War Diary of ...              2
1                              Always Have Popsicles              1

In [86]:
final_rating = rating_with_books.merge(number_rating, on='title')
final_rating.head(2)

,user_id,isbn,rating,title,author,year,publisher,image_url,no_of_ratings
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,82
1,277427,0026217457,0,Vegetarian Times Complete Cookbook,Lucy Moll,1995,John Wiley &amp; Sons,http://images.amazon.com/images/P/0026217457.0...,7

In [93]:
final_rating_filtered = final_rating[final_rating['no_of_ratings'] > 50]

In [94]:
final_rating_filtered.shape

(59903, 9)

In [100]:
final_rating_filtered.drop_duplicates(['user_id', 'title'], inplace=True)

In [105]:
final_rating_filtered.head(2)

,user_id,isbn,rating,title,author,year,publisher,image_url,no_of_ratings
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,82
1,277427,0060930535,0,The Poisonwood Bible: A Novel,Barbara Kingsolver,1999,Perennial,http://images.amazon.com/images/P/0060930535.0...,133

In [106]:
book_pivot = final_rating_filtered.pivot_table(columns='user_id', index='title', values='rating')

In [110]:
book_pivot.fillna(0, inplace=True)

In [111]:
book_pivot

user_id,254,2276,2766,2977,3363,3757,4017,4385,6242,6251,...,274004,274061,274301,274308,274808,275970,277427,277478,277639,278418
title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
84 Charing Cross Road,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,7.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [112]:
from scipy.sparse import csr_matrix

In [113]:
book_sparse = csr_matrix(book_pivot)

In [114]:
book_sparse

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 14527 stored elements and shape (703, 888)>

In [115]:
from sklearn.neighbors import NearestNeighbors
model = NearestNeighbors(algorithm='brute')

In [116]:
model.fit(book_sparse)

NearestNeighbors(algorithm='brute')

In [117]:
book_pivot.iloc[237, :]

user_id
254       0.0
2276      0.0
2766      0.0
2977      0.0
3363      0.0
         ...
275970    0.0
277427    0.0
277478    0.0
277639    0.0
278418    0.0
Name: Hemlock Bay, Length: 888, dtype: float64

In [118]:
distance, suggestion = model.kneighbors(book_pivot.iloc[237, :].values.reshape(1, -1), n_neighbors=6)

In [119]:
distance, suggestion

(array([[ 0.        , 22.53885534, 23.2594067 , 23.70653918, 23.72762104,
         23.9582971 ]]),
 array([[237, 356, 296, 305, 377, 173]]))

In [120]:
for i in range(len(suggestion)):
    print(book_pivot.index[suggestion[i]])

Index(['Hemlock Bay', 'No Safe Place', 'Last Man Standing',
       'Long After Midnight', 'Pleading Guilty', 'Exclusive'],
      dtype='object', name='title')

In [121]:
np.where(book_pivot.index == 'Pleading Guilty')[0][0]

np.int64(377)

In [126]:
ids = np.where(final_rating['title'] == "Pleading Guilty")[0][0]

In [127]:
ids

np.int64(8851)

In [128]:
final_rating.iloc[ids]['image_url']

'http://images.amazon.com/images/P/0446365505.01.LZZZZZZZ.jpg'

In [139]:
book_name = []
for book_id in suggestion:
    print(book_pivot.index[book_id])
    book_name.append(book_pivot.index[book_id])

Index(['Hemlock Bay', 'No Safe Place', 'Last Man Standing',
       'Long After Midnight', 'Pleading Guilty', 'Exclusive'],
      dtype='object', name='title')

In [140]:
book_name

[Index(['Hemlock Bay', 'No Safe Place', 'Last Man Standing',
        'Long After Midnight', 'Pleading Guilty', 'Exclusive'],
       dtype='object', name='title')]

In [143]:
ids_index = []
for name in book_name[0]:
    ids = np.where(final_rating['title'] == name)[0][0]
    ids_index.append(ids)

In [144]:
ids_index

[np.int64(244),
 np.int64(81),
 np.int64(20128),
 np.int64(266),
 np.int64(8851),
 np.int64(8858)]

In [145]:
for ids in ids_index:
    url = final_rating.iloc[ids]['image_url']
    print(url)

http://images.amazon.com/images/P/0515133302.01.LZZZZZZZ.jpg
http://images.amazon.com/images/P/0345404777.01.LZZZZZZZ.jpg
http://images.amazon.com/images/P/0446525804.01.LZZZZZZZ.jpg
http://images.amazon.com/images/P/0553571818.01.LZZZZZZZ.jpg
http://images.amazon.com/images/P/0446365505.01.LZZZZZZZ.jpg
http://images.amazon.com/images/P/0446604232.01.LZZZZZZZ.jpg

In [148]:
import pickle
pickle.dump((model, book_name, final_rating, book_pivot), open("C:/Users/y/Desktop/Academics/projects/machinelearning/book_recommendation_system/pickles/recommendation_model_names_rating_pivot.pkl", "wb"))

In [155]:
# Testing the Model Suggestion
def recommend_book(book_name):
    book_id = np.where(book_pivot.index == book_name)[0][0]
    distance, suggestion = model.kneighbors(book_pivot.iloc[book_id,:].values.reshape(1, -1), n_neighbors=6)

    for i in range(len(suggestion)):
        books = book_pivot.index[suggestion[i]]
        for j in books:
            if j == book_name:
                print(f"You searched: {book_name}\n")
                print(f"The suggestion boooks are: \n")
            else:
                print(j)

In [156]:
recommend_book('Hemlock Bay')

You searched: Hemlock Bay

The suggestion boooks are:

No Safe Place
Last Man Standing
Long After Midnight
Pleading Guilty
Exclusive